### ISSUE TITLE
See if the new version of http-signatures will work without patching

### ISSUE THREAD

**Issue by wmurphyrd** [immers-space/activitypub-express#35]
Would resolve FAQ item on InvalidHeaderError

**Comment by gregid** [comment]
I have just tried `http-signature` version 1.3.5 the `InvalidHeaderError: bad param format` is still there.

**Comment by wmurphyrd** [comment]
@gregid thanks, I'll close this then - conclusion is we need to move away from http-signatures as it is also limiting our request library options
