### ISSUE TITLE
Use status code 406 for requested content type other than application/ld+json or application/activity+json

### ISSUE THREAD

**Issue by gregid** [immers-space/activitypub-express#38]
Since the only acceptable types:
```js
  jsonldTypes: [
    'application/ld+json',
    'application/activity+json'
  ],
```
are relatively uncommon and activitypub-express at the moment uses standard `404 Not Found` I think returning status code `406 Not Acceptable` for other types with suggestion on which types to use instead in the response body could be helpful.

**Comment by wmurphyrd** [comment]
This supports both types included in the spec (note that the `profile` portion of the type string is ignored when using Express's content negotiation). What other types would you expect?

apex [does not specify a response](https://github.com/immers-space/activitypub-express/blob/master/net/validators.js#L161) for requests that don't match the ActivityPub content type  (404 is simply the default from Express when nothing is specified). That is up to the app to determine. For example, in [immers.space](https://github.com/immers-space/immers), we use content negotiation to serve both the JSON-LD object and the HTML profile page from the same URL.

Compare `curl -H "Accept: application/activity+json" https://immers.space/u/datatitian` with pointing your browser to https://immers.space/u/datatitian

If you would like to serve 406 from your app, simply add another route after the apex route that does so.

**Comment by gregid** [comment]
I don't expect any other types. 

My suggestion came from the frustration of spending time trying to figure out why I get 404 for all the routes, before I figured out the required accept type was missing. 
But the completeness of the implementation made me forget it is a library and not an application plus I am rather new to Express so thanks for pointing out the `next('route')`. Knowing this I consider the original suggestion void and if anything could be added is a small note in the usage sample on the expected types. Thanks.
