### ISSUE TITLE
jsonld.js - new version fails to load remote context

### ISSUE THREAD

**Issue by gregid** [immers-space/activitypub-express#42]
This issue is to keep track of progress in digitalbazaar/jsonld.js/issues/451

`jsonld.js` with version `5.0.0` moved away from `request` library. Unfortunately with this version the `documentLoader: jsonld.documentLoaders.node()` fails to load remote context.

If this won't be fixed and the upgrade would be needed for other reasons then possibility is to create custom documentLoader.

**Comment by wmurphyrd** [comment]
Fixed in #55 (699f079)
