### ISSUE TITLE
Skip fetching unknown actors when on some events

### ISSUE THREAD

**Issue by ClearlyClaire** [immers-space/activitypub-express#93]
It may make sense for gup.pe to skip fetching unknown actors on certain events, such as:
- a `Delete` where the `actor` and the `object` are one and the same: this is how Mastodon signals account deletions, so fetching the actor would not work (since it is deleted already), and since you don't know the actor, you have nothing to delete
- an `Update` where the `actor` and the `object` are one and the same: if you don't know the actor already, you probably don't need to process their profile updates

**Comment by wmurphyrd** [comment]
A contribution for this change would be welcome. Or, we're available for hire if you prefer: consulting@immers.space

**Comment by wmurphyrd** [comment]
The relevant code is here: https://github.com/immers-space/activitypub-express/blob/364d90705731dca755f3cb21747274eba0aad1e4/net/security.js#L44-L73

**Comment by ClearlyClaire** [comment]
Thank you for solving this issue!
